name: aqarat_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  image_picker: ^1.0.0
  firebase_storage: ^11.2.4
  wechat_assets_picker: ^8.4.3
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

