// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbYzjy-mg5FLoalvEoAR835E5Xp0wf5M',
    appId: '1:548052095349:android:a1e8a4d01ccbd38bfc433c',
    messagingSenderId: '548052095349',
    projectId: 'aqarat-5f021',
    storageBucket: 'aqarat-5f021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdJr7VSaN-uBueT0d13iQuUG9TNjsp_rM',
    appId: '1:548052095349:ios:e8d743c8335b6c4afc433c',
    messagingSenderId: '548052095349',
    projectId: 'aqarat-5f021',
    storageBucket: 'aqarat-5f021.appspot.com',
    androidClientId: '548052095349-eu6r5f1436unm8irot7bkudeqvth3et5.apps.googleusercontent.com',
    iosClientId: '548052095349-ma3r91l774ifsavvdbeh2it736orbgbu.apps.googleusercontent.com',
    iosBundleId: 'com.aqaratadmin.aqaratAdmin',
  );
}
